# Always built on x86_64
platform: linux/amd64

pipeline:
  restore-cache:
    image: drillster/drone-volume-cache
    restore: true
    mount:
      - ./.m2
    volumes:
      - /tmp/thingml-m2-cache:/cache

  build:
    image: maven:3-jdk-8
    commands:
      - mkdir -p ./.m2
      - mv ./.m2 /root/.m2
      - mvn --batch-mode -Dmaven.test.failure.ignore clean install
      - cd language
      - mvn --batch-mode -Dmaven.test.failure.ignore -pl !thingml.ui.tests install
      - mv /root/.m2 ./.m2
  
#  testing:
#    image: maven:3-jdk-8
#    commands:
#      - mkdir -p ./.m2
#      - mv ./.m2 /root/.m2
#      - mvn --batch-mode -Dmaven.test.failure.ignore test
#      - mv /root/.m2 ./.m2
    
  rebuild-cache:
    image: drillster/drone-volume-cache
    rebuild: true
    mount:
      - ./.m2
    volumes:
      - /tmp/thingml-m2-cache:/cache

  # Publish the amd64 docker container
  docker-amd64:
    group: docker
    image: plugins/docker
    dockerfile: Dockerfile-amd64
    repo: tellu/thingml
    auto_tag: true
    auto_tag_suffix: amd64
    secrets: [ docker_username, docker_password ]

  # Publish the arm32v7 docker container
  docker-arm32v7:
    group: docker
    image: plugins/docker
    dockerfile: Dockerfile-arm32v7
    repo: tellu/thingml
    auto_tag: true
    auto_tag_suffix: arm32v7
    secrets: [ docker_username, docker_password ]

clone:
  git:
    image: plugins/git
    depth: 1